import type { IndicatorHelpContent } from './IndicatorHelp'

export const MONTH_INDICATOR_HELP = {
  bankingEntries: { meaning: 'Total acumulado que entrou nas contas no período do mês.', calculation: 'Soma das movimentações com tipo bancário entrada.', includes: 'Inclui todas as entradas bancárias do período.', excludes: 'Não depende da classificação financeira e não inclui saídas.' },
  bankingExits: { meaning: 'Total acumulado que saiu das contas no período do mês.', calculation: 'Soma das movimentações com tipo bancário saída.', includes: 'Inclui gastos, investimentos, transferências e outras saídas.', excludes: 'Não inclui entradas bancárias.' },
  bankingResult: { meaning: 'Variação bancária líquida acumulada no mês.', calculation: 'Entradas bancárias menos saídas bancárias.', includes: 'Inclui todas as entradas e saídas do período.', excludes: 'Não usa classificações financeiras para selecionar movimentos.' },
  faturamento: { meaning: 'Entradas acumuladas de atividade profissional ou comercial.', calculation: 'Soma das movimentações classificadas como faturamento.', includes: 'Inclui somente faturamento.', excludes: 'Não inclui receita, transferência, estorno ou outras classificações.' },
  receita: { meaning: 'Entradas acumuladas que aumentam recursos sem serem faturamento.', calculation: 'Soma das movimentações classificadas como receita.', includes: 'Inclui somente receita.', excludes: 'Não inclui faturamento, transferências recebidas ou estornos.' },
  gastos: { meaning: 'Despesas acumuladas classificadas no período.', calculation: 'Soma das movimentações classificadas como gasto.', includes: 'Inclui somente gastos.', excludes: 'Não inclui investimentos, transferências, estornos ou não classificados.' },
  investimentos: { meaning: 'Investimentos líquidos acumulados no período.', calculation: 'Aplicações menos resgates de investimento.', includes: 'Inclui aplicações e resgates de investimento.', excludes: 'Não inclui gastos ou transferências.' },
  accumulationIndex: { meaning: 'Quanto foi investido em termos líquidos para cada unidade monetária gasta.', calculation: 'Investimentos líquidos divididos por gastos.', includes: 'Usa aplicações, resgates e gastos.', excludes: 'Não inclui outras classificações; sem gastos, o índice não é calculado.' },
  investmentPercentage: { meaning: 'Parcela configurada do faturamento destinada a investimentos.', calculation: 'Percentual informado pelo usuário.', includes: 'É aplicado somente ao faturamento acumulado.', excludes: 'Não é aplicado a receita ou entradas bancárias genéricas.' },
  operationalPercentage: { meaning: 'Parcela do faturamento disponível para a operação.', calculation: '100% menos o percentual destinado a investimentos.', includes: 'Considera a configuração de investimento.', excludes: 'Não altera faturamento, gastos ou investimentos realizados.' },
  investmentAllocation: { meaning: 'Valor planejado do faturamento destinado a investimentos.', calculation: 'Faturamento multiplicado pelo percentual de investimento.', includes: 'Usa faturamento e percentual configurado.', excludes: 'Não usa receita nem o total de investimentos realizados.' },
  operationalBudget: { meaning: 'Faturamento disponível para despesas operacionais.', calculation: 'Faturamento multiplicado pelo percentual operacional.', includes: 'Usa somente faturamento e percentual configurado.', excludes: 'Não usa receita nem entradas bancárias genéricas.' },
  realizedExpenses: { meaning: 'Gastos efetivamente classificados no período do mês.', calculation: 'Soma das movimentações classificadas como gasto.', includes: 'Inclui somente gastos realizados.', excludes: 'Não inclui investimentos ou transferências.' },
  operationalBalance: { meaning: 'Valor operacional restante depois dos gastos.', calculation: 'Orçamento operacional menos gastos realizados.', includes: 'Usa orçamento operacional e gastos.', excludes: 'Não usa receita, transferências ou investimentos realizados.' },
  dailyTarget: { meaning: 'Valor médio disponível por dia restante no período atual.', calculation: 'Saldo operacional dividido pelos dias restantes.', includes: 'Usa saldo operacional e quantidade de dias restantes.', excludes: 'Não é exibida para meses passados ou futuros.' },
  remainingDays: { meaning: 'Quantidade de dias usada para distribuir o saldo operacional.', calculation: 'Contagem inclusiva de hoje até o primeiro dia útil do próximo mês.', includes: 'Na regra atual, dia útil significa segunda a sexta-feira.', excludes: 'Não considera feriados.' },
} as const satisfies Record<string, IndicatorHelpContent>

export type MonthIndicatorId = keyof typeof MONTH_INDICATOR_HELP
